version: 0.0
os: linux
files:
  - source: target/case-yellow-gateway.jar
    destination: /home/ec2-user/case-yellow

hooks:
  AfterInstall:
    - location: scripts/stop.sh
      timeout: 180

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 180