version: 0.0
os: linux
files:
  - source: case-yellow-gateway.jar
    destination: /home/ec2-user/case-yellow

hooks:
  AfterInstall:
    - location: stop.sh
      timeout: 180
      runas: ec2-user
  ApplicationStart:
    - location: start.sh
      timeout: 180
      runas: ec2-user