version: 0.1

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
      - echo Build completed on `date`
  post_build:
    commands:
      - echo Archive cy-gateway
      - zip -r cy-gateway-archive.zip target/case-yellow-gateway.jar appspec.yml scripts/*
      - echo Uplaod cy-gateway-archive to S3
      - aws s3 cp cy-gateway-archive.zip s3://cy-codebuild/cy-gateway-build-artifact/
      - echo Successfully uplaoded cy-gateway-archive to S3

artifacts:
  files:
    - target/case-yellow-gateway.jar