version: 0.1

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
  post_build:
    commands:
      - echo Build completed on `date`
      - zip -r cy-gateway-archive.zip target/case-yellow-gateway.jar appspec.yml scripts/start.sh scripts/stop.sh
      - aws s3 cp cy-gateway-archive.zip s3://cy-codebuild/cy-gateway-build-artifact/

artifacts:
  files:
    - target/case-yellow-gateway.jar