server.port: 8008
spring.profiles.active: prod

# Services hosts
#central_url: http://localhost:9080
#analysis_url: http://localhost:7008/analysis/
central_url: http://internal-cy-internal-load-balancer-1608404301.eu-central-1.elb.amazonaws.com:9080
analysis_url: http://internal-cy-internal-load-balancer-1608404301.eu-central-1.elb.amazonaws.com:7008/analysis/

token_authentication_key: bolshit

# Logger
log.dir: /home/ec2-user/case-yellow/logs

logging:
  level:
    org.springframework.web: ERROR
    caseyellow.server.gateway: INFO
    org.hibernate: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] - %-5p %c{1}:%L - [%X{correlation-id}] - %m%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] - %-5p %c{1}:%L - [%X{correlation-id}] - %m%n"
  file: ${log.dir}/caseyellow-gateway-log

roles:
  - ADMIN
  - USER